// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSh5czEckhWAq9PXsSn9GeAGXypXCnv-8',
    appId: '1:339135253031:web:6db724ffe2690b11019c02',
    messagingSenderId: '339135253031',
    projectId: 'solveit-1337',
    authDomain: 'solveit-1337.firebaseapp.com',
    storageBucket: 'solveit-1337.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_U8VSLeguHccwSdaM31iR4yoyZRR3neM',
    appId: '1:339135253031:android:e521ddb12c6a01b9019c02',
    messagingSenderId: '339135253031',
    projectId: 'solveit-1337',
    storageBucket: 'solveit-1337.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaSU68tZvco2mAAK-lEVSpZxdwSauCzXU',
    appId: '1:339135253031:ios:27c36b4dddaebc62019c02',
    messagingSenderId: '339135253031',
    projectId: 'solveit-1337',
    storageBucket: 'solveit-1337.appspot.com',
    androidClientId: '339135253031-gmoi2jg3s51eusubo5v837a1r7u4f0s1.apps.googleusercontent.com',
    iosClientId: '339135253031-qgfooj4sdnl3me1rn5edlg52uagdf12p.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );
}
